stages:
  - test

variables:
  CI_IMAGE_PATH: registry.snapp.tech/yaus/golang-ci:1.13

lint:
  image: ${CI_IMAGE_PATH}
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  stage: test
  variables:
    GOOS: "linux"
    GOARCH: "amd64"
  script:
    - HTTP_PROXY=${PROXY} HTTPS_PROXY=${PROXY} make lint-ci
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[do-not-test\]/

test:
  image: ${CI_IMAGE_PATH}
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  stage: test
  variables:
    GOOS: "linux"
    GOARCH: "amd64"
  script:
    - HTTP_PROXY=${PROXY} HTTPS_PROXY=${PROXY} make test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[do-not-test\]/