server:
  addr: 0.0.0.0:8080
mongodb:
  uri: mongodb://localhost:27017
  database_name: yaus
redis:
  address: 127.0.0.1:6379
  password: ""
  db: 0
  max_retries: 0
  min_retry_back_off: 8ms
  max_retry_back_off: 512ms
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_size: 10
  min_idle_connections: 5
  max_connection_age: 0
  pool_timeout: 4s
  idle_timeout: 5m
  idle_check_frequency: 1m
jwt:
  ttl: 72h
  key: somesecretekey