apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: backend
      labels:
        app.snappcloud.io/name: yaus_backend
        app.snappcloud.io/managed-by: AhmadAnvari
        app: backend
    spec:
      replicas: 1
      selector:
        app: backend
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: backend
        spec:
          containers:
            - name: backend
              image: docker-registry.default.svc:5000/yaus/backend:1
              imagePullPolicy: Always
              ports:
                - containerPort: 1373
                  protocol: TCP
              resources:
                limits:
                  memory: 250Mi
          volumes:
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          terminationGracePeriodSeconds: 30

